#!/usr/bin/env python3
"""Fill kDashboardL10nByLang for Indian languages using deep-translator (no API key).

Usage (from project root):
  pip install deep-translator
  python scripts/fill_dashboard_translations_deep.py

Re-writes lib/core/l10n/dashboard_l10n.dart with en + translated maps.
"""
from __future__ import annotations

import os
import re
import sys
import time

ROOT = os.path.join(os.path.dirname(__file__), "..", "lib", "core", "l10n", "dashboard_l10n.dart")

TARGET_LANGS = ("hi", "ta", "te", "kn", "ml", "bn", "mr", "gu", "pa", "or", "ur")

PROTECTED_TOKENS = (
    "SOS",
    "EMS",
    "GPS",
    "PTT",
    "LiveKit",
    "SMS",
    "QR",
    "UID",
    "CSV",
    "Firestore",
    "Google Maps",
    "Google",
    "Lucknow",
    "AED",
    "CPR",
    "ACCEPT",
    "REFER",
    "OK",
    "UI",
    "API",
    "URL",
    "HTTP",
    "HTTPS",
    "SBAR",
    "GCP",
    "ETA",
    "PTT",
)


def dart_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def dart_unescape(s: str) -> str:
    return s.replace("\\'", "'").replace("\\\\", "\\")


def parse_en_map(text: str) -> dict[str, str]:
    lines = text.splitlines()
    in_en = False
    out: dict[str, str] = {}
    for line in lines:
        if re.search(r"'en'\s*:\s*\{", line):
            in_en = True
            continue
        if in_en and re.match(r"\s*\},\s*$", line):
            break
        if not in_en:
            continue
        mm = re.match(
            r"\s*'([^']+)':\s*'((?:\\'|[^'])*)',\s*$",
            line,
        )
        if mm:
            out[mm.group(1)] = dart_unescape(mm.group(2))
    if not out:
        raise ValueError("Could not parse 'en' map in dashboard_l10n.dart")
    return out


def protect_for_translate(s: str) -> tuple[str, dict[str, str]]:
    placeholders: dict[str, str] = {}
    out = s
    for i, tok in enumerate(PROTECTED_TOKENS):
        ph = f"__PT{i}__"
        if tok in out:
            out = out.replace(tok, ph)
            placeholders[ph] = tok
    return out, placeholders


def restore_placeholders(s: str, placeholders: dict[str, str]) -> str:
    for ph, tok in placeholders.items():
        s = s.replace(ph, tok)
    return s


def main() -> int:
    try:
        from deep_translator import GoogleTranslator
    except ImportError:
        print("Install: pip install deep-translator", file=sys.stderr)
        return 1

    text = open(ROOT, encoding="utf-8").read()
    en_map = parse_en_map(text)
    keys = sorted(en_map.keys())
    entries = [(k, en_map[k]) for k in keys]

    translated: dict[str, dict[str, str]] = {"en": dict(en_map)}

    for lang in TARGET_LANGS:
        print(f"Translating -> {lang} ({len(entries)} strings)...", flush=True)
        translator = GoogleTranslator(source="en", target=lang)
        lang_map: dict[str, str] = {}
        batch_size = 40
        for start in range(0, len(entries), batch_size):
            chunk = entries[start : start + batch_size]
            masked: list[str] = []
            ph_maps: list[dict[str, str]] = []
            for _k, v in chunk:
                m, phm = protect_for_translate(v)
                masked.append(m)
                ph_maps.append(phm)
            try:
                out = translator.translate_batch(masked)
            except Exception as e:
                print(f"Batch failed for {lang}: {e}, retrying one-by-one...", file=sys.stderr)
                out = []
                for m in masked:
                    time.sleep(0.25)
                    try:
                        out.append(translator.translate(m))
                    except Exception as e2:
                        print(f"  single fail: {e2}", file=sys.stderr)
                        out.append(m)
            if len(out) != len(chunk):
                print(f"Length mismatch {lang} batch at {start}", file=sys.stderr)
                return 1
            for (k, _orig), t, phm in zip(chunk, out, ph_maps):
                lang_map[k] = restore_placeholders(t, phm)
            time.sleep(0.35)
        translated[lang] = lang_map
        print(f"  done {lang}: {len(lang_map)}", flush=True)

    lines = [
        "// GENERATED by scripts/scan_ui_strings.py — re-run after UI string changes.",
        "// Translations: scripts/fill_dashboard_translations_deep.py (deep-translator)",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "import 'package:flutter/widgets.dart';",
        "import 'package:flutter_riverpod/flutter_riverpod.dart';",
        "",
        "import '../providers/locale_provider.dart';",
        "",
        "/// Dashboard / ops / fleet / hospital-bridge UI strings.",
        "const Map<String, Map<String, String>> kDashboardL10nByLang = {",
    ]
    for lang_code in sorted(translated.keys()):
        lines.append(f"  '{lang_code}': {{")
        for k in sorted(translated[lang_code].keys()):
            v = dart_escape(translated[lang_code][k])
            lines.append(f"    '{k}': '{v}',")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("/// English phrase → key (for [BuildContext.opsTr]).")
    lines.append("const Map<String, String> kDashboardEnglishToKey = {")
    for k in sorted(translated["en"].keys()):
        esc = dart_escape(translated["en"][k])
        lines.append(f"  '{esc}': '{k}',")
    lines.append("};")
    lines.append("")
    lines.append("extension DashboardL10nContext on BuildContext {")
    lines.append("  /// Localized dashboard string; falls back to English if missing.")
    lines.append("  String opsTr(String english) {")
    lines.append("    final key = kDashboardEnglishToKey[english];")
    lines.append("    if (key == null) return english;")
    lines.append("    final lc = _dashboardLocaleLanguageCode(this);")
    lines.append("    final langMap = kDashboardL10nByLang[lc];")
    lines.append("    final enMap = kDashboardL10nByLang['en']!;")
    lines.append("    return langMap?[key] ?? enMap[key] ?? english;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("String _dashboardLocaleLanguageCode(BuildContext context) {")
    lines.append("  try {")
    lines.append(
        "    return ProviderScope.containerOf(context, listen: false).read(localeProvider).languageCode;"
    )
    lines.append("  } catch (_) {")
    lines.append("    return Localizations.localeOf(context).languageCode;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    open(ROOT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"Wrote {ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
