#!/usr/bin/env python3
"""Fill kDashboardL10nByLang for hi, ta, te, kn, ml, bn, mr, gu, pa, or, ur using Google Cloud Translate v2.

Requires env: GOOGLE_TRANSLATE_API_KEY (API key with Cloud Translation API enabled).

Usage:
  set GOOGLE_TRANSLATE_API_KEY=...
  python scripts/generate_dashboard_translations.py
"""
from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.request

ROOT = os.path.join(os.path.dirname(__file__), "..", "lib", "core", "l10n", "dashboard_l10n.dart")

TARGET_LANGS = ("hi", "ta", "te", "kn", "ml", "bn", "mr", "gu", "pa", "or", "ur")

# Keep these English tokens in Latin/script-neutral form in translations (splice back).
PROTECTED_TOKENS = (
    "SOS",
    "EMS",
    "GPS",
    "PTT",
    "LiveKit",
    "SMS",
    "QR",
    "UID",
    "CSV",
    "Firestore",
    "Google Maps",
    "Google",
    "Lucknow",
    "LiveKit",
    "AED",
    "CPR",
    "ACCEPT",
    "REFER",
    "OK",
    "UI",
    "API",
    "URL",
    "HTTP",
    "HTTPS",
)


def dart_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def dart_unescape(s: str) -> str:
    return s.replace("\\'", "'").replace("\\\\", "\\")


def parse_en_map(text: str) -> dict[str, str]:
    lines = text.splitlines()
    in_en = False
    out: dict[str, str] = {}
    for line in lines:
        if re.search(r"'en'\s*:\s*\{", line):
            in_en = True
            continue
        if in_en and re.match(r"\s*\},\s*$", line):
            break
        if not in_en:
            continue
        mm = re.match(
            r"\s*'([^']+)':\s*'((?:\\'|[^'])*)',\s*$",
            line,
        )
        if mm:
            out[mm.group(1)] = dart_unescape(mm.group(2))
    if not out:
        raise ValueError("Could not parse 'en' map in dashboard_l10n.dart")
    return out


def translate_batch(
    api_key: str, texts: list[str], target: str
) -> list[str]:
    """Returns translated strings in same order."""
    url = f"https://translation.googleapis.com/language/translate/v2?key={api_key}"
    body = json.dumps({
        "q": texts,
        "target": target,
        "format": "text",
    }).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    translations = data["data"]["translations"]
    return [t["translatedText"] for t in translations]


def protect_for_translate(s: str) -> tuple[str, dict[str, str]]:
    """Replace protected tokens with placeholders."""
    placeholders: dict[str, str] = {}
    out = s
    for i, tok in enumerate(PROTECTED_TOKENS):
        ph = f"__PT{i}__"
        if tok in out:
            out = out.replace(tok, ph)
            placeholders[ph] = tok
    return out, placeholders


def restore_placeholders(s: str, placeholders: dict[str, str]) -> str:
    for ph, tok in placeholders.items():
        s = s.replace(ph, tok)
    return s


def main() -> int:
    api_key = os.environ.get("GOOGLE_TRANSLATE_API_KEY", "").strip()
    if not api_key:
        print(
            "GOOGLE_TRANSLATE_API_KEY not set — skipping translation "
            "(English map unchanged).",
            file=sys.stderr,
        )
        return 0

    text = open(ROOT, encoding="utf-8").read()
    en_map = parse_en_map(text)
    keys = list(en_map.keys())
    entries = [(k, en_map[k]) for k in keys]

    translated: dict[str, dict[str, str]] = {"en": dict(en_map)}

    for lang in TARGET_LANGS:
        lang_map: dict[str, str] = {}
        batch_size = 40
        for start in range(0, len(entries), batch_size):
            chunk = entries[start : start + batch_size]
            to_send: list[str] = []
            ph_maps: list[dict[str, str]] = []
            for _k, v in chunk:
                masked, phm = protect_for_translate(v)
                to_send.append(masked)
                ph_maps.append(phm)
            try:
                out = translate_batch(api_key, to_send, lang)
            except urllib.error.HTTPError as e:
                print(f"HTTP error for {lang}: {e.read().decode()}", file=sys.stderr)
                return 1
            for (k, _orig), t, phm in zip(chunk, out, ph_maps):
                lang_map[k] = restore_placeholders(t, phm)
            time.sleep(0.15)
        translated[lang] = lang_map
        print(f"Translated {lang}: {len(lang_map)} strings")

    # Rebuild dashboard_l10n.dart (preserve extension + reverse map)
    ext = ""
    if "/// English phrase" in text:
        ext = text[text.index("/// English phrase") :]
    else:
        ext = ""

    lines = [
        "// GENERATED by scripts/scan_ui_strings.py — re-run after UI string changes.",
        "// Translations: scripts/generate_dashboard_translations.py",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "import 'package:flutter/widgets.dart';",
        "",
        "/// Dashboard / ops / fleet / hospital-bridge UI strings.",
        "const Map<String, Map<String, String>> kDashboardL10nByLang = {",
    ]
    for lang_code in sorted(translated.keys()):
        lines.append(f"  '{lang_code}': {{")
        for k in sorted(translated[lang_code].keys()):
            v = dart_escape(translated[lang_code][k])
            lines.append(f"    '{k}': '{v}',")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # Rebuild reverse map from English keys only
    lines.append("/// English phrase → key (for [BuildContext.opsTr]).")
    lines.append("const Map<String, String> kDashboardEnglishToKey = {")
    for k in sorted(translated["en"].keys()):
        esc = dart_escape(translated["en"][k])
        lines.append(f"  '{esc}': '{k}',")
    lines.append("};")
    lines.append("")
    lines.append("extension DashboardL10nContext on BuildContext {")
    lines.append("  /// Localized dashboard string; falls back to English if missing.")
    lines.append("  String opsTr(String english) {")
    lines.append("    final key = kDashboardEnglishToKey[english];")
    lines.append("    if (key == null) return english;")
    lines.append("    final lc = Localizations.localeOf(this).languageCode;")
    lines.append("    final langMap = kDashboardL10nByLang[lc];")
    lines.append("    final enMap = kDashboardL10nByLang['en']!;")
    lines.append("    return langMap?[key] ?? enMap[key] ?? english;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    open(ROOT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"Wrote {ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
