"""Scan dashboard Dart files for UI string literals; emit dashboard_l10n.dart."""
import hashlib
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..", "lib")
DIRS = [
    os.path.join(ROOT, "features", "staff", "presentation"),
    os.path.join(ROOT, "features", "hospital_bridge", "presentation"),
    os.path.join(ROOT, "features", "operations", "presentation"),
]


def slug(s: str, max_len: int = 40) -> str:
    h = hashlib.sha1(s.encode("utf-8")).hexdigest()[:10]
    base = re.sub(r"[^a-z0-9]+", "_", s.lower())[:max_len].strip("_")
    if not base:
        base = "s"
    return f"{base}_{h}"


def extract_strings_from_line(line: str) -> list[str]:
    """Extract likely UI strings from one line (single-quoted)."""
    out = []
    # After migration: context.opsTr('...')
    for rx in (
        r"context\.opsTr\(\s*'((?:\\'|[^'])*)'",
        r'context\.opsTr\(\s*"((?:\\"|[^"])*)"',
    ):
        for m in re.finditer(rx, line):
            s = m.group(1)
            if "\\'" in s:
                s = s.replace("\\'", "'")
            if '\\"' in s:
                s = s.replace('\\"', '"')
            out.append(s)
    # Text('...') / const Text('...')
    for rx in (
        r"(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"child:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"label:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r'Text\(\s*"((?:\\"|[^"])*)"',
        r"subtitle:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r'subtitle:\s*(?:const\s+)?Text\(\s*"((?:\\"|[^"])*)"',
        r"label:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"content:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"content:\s*Text\(\s*'((?:\\'|[^'])*)'",
        r"title:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"title:\s*Text\(\s*'((?:\\'|[^'])*)'",
        r"child:\s*(?:const\s+)?Text\(\s*'((?:\\'|[^'])*)'",
        r"labelText:\s*'((?:\\'|[^'])*)'",
        r"hintText:\s*'((?:\\'|[^'])*)'",
        r"tooltip:\s*'((?:\\'|[^'])*)'",
        r"semanticLabel:\s*'((?:\\'|[^'])*)'",
    ):
        for m in re.finditer(rx, line):
            s = m.group(1)
            if "\\'" in s:
                s = s.replace("\\'", "'")
            if '\\"' in s:
                s = s.replace('\\"', '"')
            out.append(s)
    return out


def main():
    seen = {}
    for d in DIRS:
        if not os.path.isdir(d):
            continue
        for dirpath, _, files in os.walk(d):
            for fn in files:
                if not fn.endswith(".dart"):
                    continue
                path = os.path.join(dirpath, fn)
                try:
                    lines = open(path, encoding="utf-8").readlines()
                except OSError:
                    continue
                for line in lines:
                    for s in extract_strings_from_line(line):
                        if not s or len(s) > 280:
                            continue
                        if "$" in s or "${" in s:
                            continue
                        if s.strip() == "":
                            continue
                        seen.setdefault(s, path)

    items = []
    for s in sorted(seen.keys()):
        key = "ops_" + slug(s)
        items.append((key, s))

    # Reverse map: English -> key (last wins if duplicate values — should not happen)
    rev = {v: k for k, v in items}

    out = []
    out.append("// GENERATED by scripts/scan_ui_strings.py — re-run after UI string changes.")
    out.append("// ignore_for_file: lines_longer_than_80_chars")
    out.append("")
    out.append("import 'package:flutter/widgets.dart';")
    out.append("")
    out.append("/// Dashboard / ops / fleet / hospital-bridge UI strings.")
    out.append("/// Run scripts/generate_translations.dart to add hi, ta, …")
    out.append("const Map<String, Map<String, String>> kDashboardL10nByLang = {")
    out.append("  'en': {")
    for key, s in items:
        esc = s.replace("\\", "\\\\").replace("'", "\\'")
        out.append(f"    '{key}': '{esc}',")
    out.append("  },")
    out.append("};")
    out.append("")
    out.append("/// English phrase → key (for [BuildContext.opsTr]).")
    out.append("const Map<String, String> kDashboardEnglishToKey = {")
    for s in sorted(rev.keys()):
        esc = s.replace("\\", "\\\\").replace("'", "\\'")
        out.append(f"  '{esc}': '{rev[s]}',")
    out.append("};")
    out.append("")
    out.append("extension DashboardL10nContext on BuildContext {")
    out.append("  /// Localized dashboard string; falls back to English if missing.")
    out.append("  String opsTr(String english) {")
    out.append("    final key = kDashboardEnglishToKey[english];")
    out.append("    if (key == null) return english;")
    out.append("    final lc = Localizations.localeOf(this).languageCode;")
    out.append("    final langMap = kDashboardL10nByLang[lc];")
    out.append("    final enMap = kDashboardL10nByLang['en']!;")
    out.append("    return langMap?[key] ?? enMap[key] ?? english;")
    out.append("  }")
    out.append("}")
    out.append("")

    target = os.path.join(ROOT, "core", "l10n", "dashboard_l10n.dart")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"Wrote {len(items)} EN strings + reverse map to {target}")


if __name__ == "__main__":
    main()
