import 'package:flutter/material.dart';

/// Universal "AI advisory" banner shown on every Gemini-backed surface in
/// EmergencyOS (triage, Lifeline chat, ops analytics, situation brief). It
/// keeps the messaging, styling, and legal disclaimer consistent and makes it
/// obvious to reviewers / judges that every AI output is assistive, not a
/// clinical diagnosis.
///
/// Variants:
///   * [AiAdvisoryBanner.triage] — for clinical triage surfaces.
///   * [AiAdvisoryBanner.lifeline] — for first-aid chat / voice copilot.
///   * [AiAdvisoryBanner.analytics] — for ops analytics chat.
///   * [AiAdvisoryBanner.brief] — for the shared situation brief card.
class AiAdvisoryBanner extends StatelessWidget {
  const AiAdvisoryBanner({
    super.key,
    required this.message,
    this.icon = Icons.auto_awesome_rounded,
    this.accent = const Color(0xFFFFB74D),
    this.dense = false,
  });

  /// Convenience constructor for clinical triage surfaces.
  factory AiAdvisoryBanner.triage({bool dense = false}) => AiAdvisoryBanner(
        message:
            'AI ADVISORY: Triage is generated by Gemini Flash. This is an assistive tool, NOT a professional medical diagnosis. On-scene qualified personnel make the final call.',
        icon: Icons.health_and_safety_rounded,
        dense: dense,
      );

  /// Convenience constructor for Lifeline first-aid chat / voice copilot.
  factory AiAdvisoryBanner.lifeline({bool dense = false}) => AiAdvisoryBanner(
        message:
            'AI ADVISORY: Lifeline is a Gemini-powered first-aid copilot, not a clinician. For life-threatening signs, call 112 immediately.',
        icon: Icons.support_agent_rounded,
        dense: dense,
      );

  /// Convenience constructor for ops analytics chat surfaces.
  factory AiAdvisoryBanner.analytics({bool dense = false}) => AiAdvisoryBanner(
        message:
            'AI ADVISORY: Operational insights are generated by Gemini on live Firestore data. Verify numbers before dispatching resources.',
        icon: Icons.insights_rounded,
        accent: const Color(0xFF64B5F6),
        dense: dense,
      );

  /// Convenience constructor for the shared situation brief card.
  factory AiAdvisoryBanner.brief({bool dense = false}) => AiAdvisoryBanner(
        message:
            'AI ADVISORY: Situation briefs are synthesized by Gemini from scene reports, photos, and incident metadata. Do not treat as ground truth without field confirmation.',
        icon: Icons.article_rounded,
        accent: const Color(0xFFBA68C8),
        dense: dense,
      );

  final String message;
  final IconData icon;
  final Color accent;
  final bool dense;

  @override
  Widget build(BuildContext context) {
    final pad = dense
        ? const EdgeInsets.symmetric(horizontal: 10, vertical: 8)
        : const EdgeInsets.all(12);
    final fontSize = dense ? 10.0 : 11.0;
    return Container(
      padding: pad,
      decoration: BoxDecoration(
        color: accent.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: accent.withValues(alpha: 0.25)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: accent, size: dense ? 14 : 16),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              message,
              style: TextStyle(
                color: accent,
                fontSize: fontSize,
                height: 1.4,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
